---
# If we structure our desired state based off the YANG model, then
# we can easily consume the data when assembling the edit-config RPC.
intf:
  eth1/1:
    interface-mode: "ACCESS"
    access-vlan: 11
  eth1/2:
    interface-mode: "ACCESS"
    access-vlan: 12
  eth1/3:
    interface-mode: "TRUNK"
    native-vlan: 13
...
